package Entities;

public enum CommandType {
    NO_COMMAND,
    VIEW_AVAILABLE_INGREDIENTS,
    ORDER_SPECIFIC_INGREDIENTS,
    VIEW_TOTAL_SALES,
    VIEW_TOTAL_EXPENSES,
    VIEW_TOTAL_PROFIT,
    PLACE_ORDER,
    EXIT,
    INPUT_INGREDIENT_QTY,
    ORDER_MULTIPLE_INGREDIENTS,
    FINALIZE_ORDER
}
